services:
  backend:
    build:
      context: ./bytebank-api
    ports:
      - "3003:3003"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  microfrontend:
    build:
      context: ./bytebank-ui/microfrontends/transfers-mf
    ports:
      - "4201:4201"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./bytebank-ui
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:3003}
        TRANSFERS_DOMAIN: ${TRANSFERS_DOMAIN:-http://microfrontend:4201}
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - microfrontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
